### ISSUE TITLE
monoidal-containers needs an new upload to Hackage

### ISSUE THREAD

**Issue by erikd** [haskell-infra/hackage-trustees#401]
The version on Github compiles with `ghc-9.10` but the version on Hackage does not. For example:
```
src/Data/IntMap/Monoidal.hs:54:7: error: [GHC-87543]
    Ambiguous occurrence ‘foldl'’.
    It could refer to
       either ‘Prelude.foldl'’,
              imported from ‘Prelude’ at src/Data/IntMap/Monoidal.hs:130:1-63
              (and originally defined in ‘ghc-internal-9.1001.0:GHC.Internal.Data.Foldable’),
           or ‘Data.IntMap.Monoidal.foldl'’,
              defined at src/Data/IntMap/Monoidal.hs:473:1.
   |
54 |     , foldl'
   |       ^^^^^^
```
This has been raised as an issue in https://github.com/bgamari/monoidal-containers/issues/106 and was told that this was likley fixed in https://github.com/bgamari/monoidal-containers/pull/105 and that the Hackage metadata was updated. 

However, a Hackage metadata update is not sufficient. A fix would be to uplaod a new package based on the code on Github.

**Comment by ali-abrar** [comment]
Thanks for pointing this out. Uploaded.

**Comment by erikd** [comment]
Confirmed! Thanks.
