### ISSUE TITLE
packages missing upper bound against primitive-0.7

### ISSUE THREAD

**Issue by vmchale** [haskell-infra/hackage-trustees#228]
As of writing, `hashtables` fails to compile, breaking Agda among other things. 

cc @gregorycollins

**Comment by cartazio** [comment]
https://github.com/gregorycollins/hashtables/pull/56 is a patch that can be applied

**Comment by cartazio** [comment]
i'll bulk edit a < 0.7 bound

**Comment by hvr** [comment]
I've re-purposed this ticket to act as container for all packages that are broken by primitive-0.7 due to lack of upper bounds

**Comment by cartazio** [comment]
for now i'm gonna do the fix on hashtables, haven't looked at broader stuff yet :)

**Comment by cartazio** [comment]
@vmchale cabal update again and you should be good :)

**Comment by vmchale** [comment]
Looks like the latest release of `hashtables` broke again: https://matrix.hackage.haskell.org/#/package/hashtables

**Comment by hvr** [comment]
Fixed up via https://hackage.haskell.org/package/hashtables-1.2.3.2/revisions/ by @gwils as well as reported upstream at https://github.com/gregorycollins/hashtables/pull/58

**Comment by hvr** [comment]
Another one is @jberryman's https://matrix.hackage.haskell.org/package/unagi-chan@1559401812 (already fixed up via revisions, see e.g.  https://hackage.haskell.org/package/unagi-chan-0.4.1.0/revisions/)

**Comment by cartazio** [comment]
someone needs to pester them to release versions that *build* with it :)

**Comment by hvr** [comment]
Here's a weird one: https://matrix.hackage.haskell.org/package/primitive-extras@1559407535

`primitive-extras-0.7.1.1` got released ~2 weeks ago whose only change relative to primitive-extras-0.7.1 was a version-bound relaxation allowing `primitive-0.7` (see http://hdiff.luite.com/cgit/primitive-extras/diff?id=0.7.1.1&id2=0.7.1 -- i.e. should have had been accomplished via a Hackage metadata revision instead of a full release) but does **not** work with `primitive-0.7` (`Not in scope: type constructor or class ‘UnliftedArray’` -- which in fact was removed from the API in `primitive-0.7`).

I've already fixed it up via https://hackage.haskell.org/package/primitive-extras-0.7.1.1/revisions/ (which effectively makes `primitive-extras-0.7.1.1` a redundant release as it's effectively the same as `primitive-0.7.1` now except having a different version number); and while at it I also fixed up the 17 broken primitive-extras releases v0.1.10 through v0.3 via metadata revisions; the resulting build report can be inspected at https://matrix.hackage.haskell.org/package/primitive-extras@1559409428


cc @nikita-volkov

**Comment by nikita-volkov** [comment]
@hvr Just fixed these things and uploaded the packages. Thanks for informing!

**Comment by andreasabel** [comment]
Closing...  If there remains anything to be done here, please reopen with a bullet list (or open a new issue).
