### ISSUE TITLE
scidb-hquery package dependencies failed to build: 2019-10-04T23:13:21Z 

### ISSUE THREAD

**Issue by mdgabriel** [haskell-infra/hackage-trustees#248]
This is a low priority package because no package depends on it and it fits a niche group.  I am the package maintainer of scidb-hquery.

Index-state 2019-10-04T23:13:21Z for my package scidb-hquery 2.8.0.x failed to build because package dependencies failed to build.  All previous builds succeeded.  What truly confuses me is that my local build with cabal 2.4.x using v2-build, the new style of build, has also stopped working.  The compiler is ghc 8..6.5  and the problematic dependency appears to be either regex-1.0.0.0 and regex-1.0.2.0:

> [30 of 47] Compiling Text.RE.ZeInternals.SearchReplace ( Text/RE/ZeInternals/SearchReplace.hs, dist/build/Text/RE/
> ZeInternals/SearchReplace.o )
> 
> Text/RE/ZeInternals/SearchReplace.hs:47:55: error:
>     • Could not deduce (MonadFail m) arising from a use of ‘fail’
>       from the context: Monad m
>         bound by the type signature for:
>                    compileSearchReplace_ :: forall (m :: * -> *) s re.
>                                             (Monad m, Functor m) =>
>                                             (String -> s)
>                                             -> (String -> Either String re)
>                                             -> String
>                                             -> m (SearchReplace re s)
>         at Text/RE/ZeInternals/SearchReplace.hs:(42,1)-(46,47)
> 

As far as I can tell nothing has "changed," but obviously something has changed, and I do not know how to proceed if I want to upload a new version.

Note that my package builds with stack using resolvers from lts-13.19 to lts-14.14.

**Comment by phadej** [comment]
It's `regex`, see https://matrix.hackage.haskell.org/#/package/regex

This is https://github.com/haskell-infra/hackage-trustees/issues/243 problem.

I'll look at this tomorrow (Tuesday 2019-11-12) if no other trustee beats me on that.

**Comment by mdgabriel** [comment]
You are corrected about `base-compat-0.11`.  If in regex-1.0.2.0 I replace in regex.cabal the line
>       , base-compat          >= 0.6
with
>       , base-compat          >= 0.6      && < 0.11
then regex-1.0.2.0 complies once again.  in `Changes in 0.11.0 [2019.09.06]`, there was a backport of `MonadFail(fail)` to `Prelude.Compat` and `Control.Monad.Compat` which is generating the error
> Could not deduce (MonadFail m) arising from a use of ‘fail’ from the context: Monad m

**Comment by mdgabriel** [comment]
By the way, thanks for the hint about base-compat-0.11.

**Comment by mdgabriel** [comment]
Adding
> base-compat          >= 0.6      && < 0.11
to my package of course fixes my problem so for me this case can be closed since I have uploaded a new version that now compiles with proper constraints.

**Comment by phadej** [comment]
https://matrix.hackage.haskell.org/#/package/regex/1.0.2.0/ghc-7.10.3@1573730518

reviewed `regex` bounds
