### ISSUE TITLE
haddock-api-2.17.3 fails to build with GHC 8.0.2

### ISSUE THREAD

**Issue by RyanGlScott** [haskell-infra/hackage-trustees#90]
`haddock-api-2.17.3` from Hackage fails to build with GHC 8.0.2, as observed [here](https://travis-ci.org/gtk2hs/gtk2hs/jobs/189834962#L353):

```
[ 8 of 38] Compiling Haddock.Types    ( src/Haddock/Types.hs, dist/build/Haddock/Types.o )

src/Haddock/Types.hs:451:10: error:
    Duplicate instance declarations:
      instance NFData Name -- Defined at src/Haddock/Types.hs:451:10
      instance NFData Name -- Defined in ‘Name’

src/Haddock/Types.hs:452:10: error:
    Duplicate instance declarations:
      instance NFData OccName -- Defined at src/Haddock/Types.hs:452:10
      instance NFData OccName -- Defined in ‘OccName’

src/Haddock/Types.hs:453:10: error:
    Duplicate instance declarations:
      instance NFData ModuleName
        -- Defined at src/Haddock/Types.hs:453:10
      instance NFData ModuleName -- Defined in ‘Module’
```

Should the upper version bound on `ghc` be edited to `< 8.0.2`?

**Comment by bergmark** [comment]
Looks like it, I published new revisions for 2.17.3 and 2.17.2.

Has this/should this be reported elsewhere?

**Comment by RyanGlScott** [comment]
I'm quite confused about what's going on myself, since the version of `haddock` that's shipped with GHC 8.0.2 itself is 2.17.3:

```
$ /opt/ghc/8.0.2/bin/haddock --version
Haddock version 2.17.3, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008
```

**Comment by bgamari** [comment]
The problem here is that `ghc` 8.0.2 contains a orphan instances that 8.0.1 did not. It appears that `haddock` also defines these same orphans. Kaboom ensues.

Thankfully these orphans will be in `deepseq` as they should be (IIRC) in 8.2.

**Comment by RyanGlScott** [comment]
Wait, I'm even more confused.

> Thankfully these orphans will be in `deepseq` as they should be (IIRC) in 8.2.

Surely not? After all, these instances are for datatypes in the GHC API, which have no business belonging in `deepseq`.

Also, will there be a Hackage release of the version of `haddock`(`-api`) that is apparently bundled with GHC 8.0.2?

**Comment by RyanGlScott** [comment]
See also https://github.com/haskell/haddock/issues/571

**Comment by RyanGlScott** [comment]
[`haddock-api-2.17.3.1`](http://hackage.haskell.org/package/haddock-api-2.17.3.1) has been uploaded to Hackage, which supports GHC 8.0.2.
